device: "cpu"
resume_training: false
n_envs: 1
hyperparameters:
  clip_obs: 10
  learning_rate: 0.001
  net_arch: 
    - 256
    - 256
  buffer_size: 200000
  learning_starts: 10000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 
    - 1
    - "episode"
  gradient_steps: -1
  action_noise:
    mean: [0.0, 0.0, 0.0, 0.0]
    sigma: [0.1, 0.1, 0.1, 0.1]
  total_timesteps: 1000000