# action_mode: "indirect"
# device: "cpu"
# n_envs: 6
# resume_training: False
# visualize: False
# hyperparameters:
#   clip_obs: 10
#   net_arch: 
#     - 256
#     - 256
#   learning_rate: 0.0003
#   buffer_size: 200000
#   learning_starts: 10000
#   batch_size: 256
#   tau: 0.005
#   gamma: 0.99
#   train_freq: [500, "step"] #[1, "episode"]
#   gradient_steps: -1
#   ent_coef: 'auto'
#   total_timesteps: 100000
#   feature_extractor: "transformer"
#   history_len: 5

action_mode: "indirect"
device: "cpu"
n_envs: 8
resume_training: True
visualize: False
hyperparameters:
  clip_obs: 100
  net_arch: 
    - 64
    - 256
    - 256
  learning_rate: 0.0003
  buffer_size: 250000
  learning_starts: 10000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: [500, "step"] #[1, "episode"]
  gradient_steps: -1
  ent_coef: 'auto'
  total_timesteps: 100000 #1443232
  feature_extractor: "transformer"
  history_len: 15