agent_mode: "indirect"
device: "cpu"
resume: False
hyperparameters:
  net_arch:
    - 1028
    - 1028
  optimizer_lr: 3e-4
  l2_weight: 1e-4
  ent_weight: 1e-3
  batch_size: 10
  n_epochs: 10
  feature_encoder: "transformer"
  history_len: 5