imitation_mode: "indirect"
device: "cpu"
n_envs: 2
resume_training: True
hyperparameters:
  clip_obs: 10
  n_steps: 10
  net_arch:
    - 256
    - 256
  hid_sizes:
    - 256 
    - 256
  batch_size: 20
  demo_batch_size: 512
  gen_replay_buffer_capacity: 8192
  n_disc_updates_per_round: 4
  total_timesteps: 150
  feature_extractor: "transformer"
  history_len: 5

