action_mode: "indirect"
device: "cpu"
resume_training: True
n_envs: 1
hyperparameters:
  clip_obs: 10
  net_arch: 
    - 256
    - 256
  learning_rate: 0.0003
  buffer_size: 200000
  learning_starts: 10000
  batch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: [1, "episode"]
  gradient_steps: -1
  ent_coef: 'auto'
  total_timesteps: 10
  feature_extractor: "transformer"
  history_len: 5