action_mode: "indirect"
device: "cpu"
resume_training: False
hyperparameters:
  clip_obs: 10
  net_arch:
    - 256
    - 256
  optimizer_lr: 3e-4
  l2_weight: 1e-4
  ent_weight: 1e-3
  batch_size: 100
  n_epochs: 1000
  feature_encoder: "transformer"
  history_len: 5