hold: 320
n: NULL
pos:
  kp: 
    - 120.0 # x
    - 120.0 # y
    - 120.0 # z

  kd: 
    - 20.0 # x
    - 20.0 # y
    - 20.0 # z

  ki:
    - 25.00 # x
    - 25.00 # y
    - 25.00 # z

rot:
  kp: 
    - 35.0 # rx
    - 15.0 # ry
    - 15.0 # rz

  kd: 
    - 2.00 # rx
    - 2.00 # ry
    - 2.00 # rz

  ki:
  - 1.00 # x
  - 1.00 # y
  - 1.00 # z