hold: 120
n: NULL
pos:
  kp: 
    - 1580.0 # x
    - 1580.0 # y
    - 1580.0 # z

  kd: 
    - 200.0 # x
    - 200.0 # y
    - 200.0 # z

  ki:
    - 25.00 # x
    - 25.00 # y
    - 25.00 # z


rot:
  kp: 
    - 5.0 # rx
    - 5.0 # ry
    - 5.0 # rz

  kd: 
    - 2.00 # rx
    - 2.00 # ry
    - 2.00 # rz
    
  ki:
    - 1.00 # x
    - 1.00 # y
    - 1.00 # z