hold: 320
n: NULL
pos:
  kp: 
    - 20.0 # Shoulder Pan
    - 60.0 # Shoulder Lift
    - 20.0 # Elbow
    - 20.0 # Wrist 1
    - 20.0 # Wrist 2
    - 10.0 # Wrist 3

  kd: 
    - 5.00 # Shoulder Pan
    - 15.0 # Shoulder Lift
    - 5.00 # Elbow
    - 5.00 # Wrist 1
    - 5.00 # Wrist 2
    - 20.0 # Wrist 3

  ki:
    - 5.00 # Shoulder Pan
    - 5.00 # Shoulder Lift
    - 2.00 # Elbow
    - 2.00 # Wrist 1
    - 2.00 # Wrist 2
    - 1.50 # Wrist 3



rot:
  kp: 
    - 5.02 # Shoulder Pan
    - 5.01 # Shoulder Lift
    - 5.80 # Elbow
    - 5.80 # Wrist 1
    - 5.09 # Wrist 2
    - 5.80 # Wrist 3

  kd: 
    - 5.00 # Shoulder Pan
    - 50.0 # Shoulder Lift
    - 10.0 # Elbow
    - 5.0 # Wrist 1
    - 5.0 # Wrist 2
    - 5.0 # Wrist 3

  ki:
    - 0.02 # Shoulder Pan
    - 0.05 # Shoulder Lift
    - 0.10 # Elbow
    - 0.50 # Wrist 1
    - 0.10 # Wrist 2
    - 0.50 # Wrist 3
